queryUrl: http://localhost:9093
clusterName:
webhookUrl:
slackClient:
  userName:
  channel:
alertRulesList:
  - alertname: "haproxyBackendSizeDivergence"
    enabled: true
    action: "deletePod"
  - alertname: "test"
    enabled: true
    action: "deletePod"
