name: Go Test

on:
  pull_request: {}

jobs:
  linting:
    name: Go lint
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: '>=1.18.0'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2

    - name: go-test
      run: |
        go test -v ./kuberemediate/
        go test -v ./notification/
